name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: master

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: master
          command: android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: ${{ steps.buildozer.outputs.filename }}
